normalTags = {
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Ecchi",
    "Fantasy",
    "Horror",
    "Mahou Shoujo",
    "Mecha",
    "Music",
    "Mystery",
    "Psychological",
    "Romance",
    "Sci-Fi",
    "Slice of Life",
    "Sports",
    "Supernatural",
    "Thriller",
    "Hentai",
    "Anti-Hero",
    "Ensemble Cast",
    "Female Protagonist",
    "Male Protagonist",
    "Primarily Adult Cast",
    "Primarily Child Cast",
    "Primarily Female Cast",
    "Primarily Male Cast",
    "Primarily Teen Cast",
    "Age Regression",
    "Agender",
    "Aliens",
    "Amnesia",
    "Angels",
    "Artificial Intelligence",
    "Asexual",
    "Butler",
    "Centaur",
    "Chimera",
    "Chuunibyou",
    "Clone",
    "Cosplay",
    "Crossdressing",
    "Cyborg",
    "Delinquents",
    "Demons",
    "Detective",
    "Dinosaurs",
    "Disability",
    "Dissociative Identities",
    "Dragons",
    "Dullahan",
    "Elf",
    "Ghost",
    "Goblin",
    "Gods",
    "Gyaru",
    "Hikikomori",
    "Idol",
    "Kemonomimi",
    "Kuudere",
    "Maids",
    "Mermaid",
    "Monster Boy",
    "Monster Girl",
    "Nekomimi",
    "Ninja",
    "Nudity",
    "Nun",
    "Office Lady",
    "Oiran",
    "Ojou-sama",
    "Pirates",
    "Robots",
    "Samurai",
    "Shrine Maiden",
    "Skeleton",
    "Succubus",
    "Tanned Skin",
    "Teacher",
    "Tomboy",
    "Transgender",
    "Tsundere",
    "Twins",
    "Vampire",
    "Vikings",
    "Villainess",
    "VTuber",
    "Werewolf",
    "Witch",
    "Yandere",
    "Zombie",
    "Josei",
    "Kids",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Bar",
    "Circus",
    "College",
    "Dungeon",
    "Foreign",
    "Language Barrier",
    "Outdoor",
    "Rural",
    "School",
    "School Club",
    "Urban",
    "Work",
    "Achronological Order",
    "Anachronism",
    "Dystopian",
    "Historical",
    "Time Skip",
    "Afterlife",
    "Alternate Universe",
    "Augmented Reality",
    "Omegaverse",
    "Post-Apocalyptic",
    "Space",
    "Urban Fantasy",
    "Virtual World",
    "4-koma",
    "Achromatic",
    "Advertisement",
    "Anthology",
    "CGI",
    "Episodic",
    "Flash",
    "Full CGI",
    "Full Color",
    "No Dialogue",
    "Non-fiction",
    "POV",
    "Puppetry",
    "Rotoscoping",
    "Stop Motion",
    "Travel",
    "Archery",
    "Battle Royale",
    "Espionage",
    "Fugitive",
    "Guns",
    "Martial Arts",
    "Swordplay",
    "Acting",
    "Calligraphy",
    "Classic Literature",
    "Drawing",
    "Fashion",
    "Food",
    "Makeup",
    "Photography",
    "Rakugo",
    "Writing",
    "Band",
    "Dancing",
    "Musical",
    "Parody",
    "Satire",
    "Slapstick",
    "Surreal Comedy",
    "Bullying",
    "Coming of Age",
    "Conspiracy",
    "Rehabilitation",
    "Revenge",
    "Suicide",
    "Tragedy",
    "Body Swapping",
    "Cultivation",
    "Fairy Tale",
    "Henshin",
    "Isekai",
    "Kaiju",
    "Magic",
    "Mythology",
    "Necromancy",
    "Shapeshifting",
    "Steampunk",
    "Super Power",
    "Superhero",
    "Wuxia",
    "Youkai",
    "E-Sports",
    "Video Games",
    "Card Battle",
    "Go",
    "Karuta",
    "Mahjong",
    "Poker",
    "Shogi",
    "Airsoft",
    "American Football",
    "Athletics",
    "Badminton",
    "Baseball",
    "Basketball",
    "Boxing",
    "Cheerleading",
    "Cycling",
    "Fencing",
    "Fishing",
    "Fitness",
    "Football",
    "Golf",
    "Ice Skating",
    "Judo",
    "Lacrosse",
    "Parkour",
    "Rugby",
    "Scuba Diving",
    "Skateboarding",
    "Sumo",
    "Surfing",
    "Swimming",
    "Table Tennis",
    "Tennis",
    "Volleyball",
    "Wrestling",
    "Adoption",
    "Animals",
    "Astronomy",
    "Autobiographical",
    "Biographical",
    "Body Horror",
    "Cannibalism",
    "Chibi",
    "Cosmic Horror",
    "Crime",
    "Crossover",
    "Death Game",
    "Denpa",
    "Drugs",
    "Economics",
    "Educational",
    "Environmental",
    "Ero Guro",
    "Gambling",
    "Gender Bending",
    "Gore",
    "LGBTQ+ Themes",
    "Lost Civilization",
    "Medicine",
    "Memory Manipulation",
    "Meta",
    "Noir",
    "Otaku Culture",
    "Pandemic",
    "Philosophy",
    "Politics",
    "Reincarnation",
    "Religion",
    "Slavery",
    "Software Development",
    "Survival",
    "Terrorism",
    "Torture",
    "War",
    "Assassins",
    "Cult",
    "Firefighters",
    "Gangs",
    "Mafia",
    "Military",
    "Police",
    "Triads",
    "Yakuza",
    "Aviation",
    "Cars",
    "Mopeds",
    "Motorcycles",
    "Ships",
    "Tanks",
    "Trains",
    "Age Gap",
    "Bisexual",
    "Boys' Love",
    "Female Harem",
    "Heterosexual",
    "Love Triangle",
    "Male Harem",
    "Teens' Love",
    "Yuri",
    "Cyberpunk",
    "Space Opera",
    "Time Manipulation",
    "Tokusatsu",
    "Real Robot",
    "Super Robot",
    "Agriculture",
    "Cute Boys Doing Cute Things",
    "Cute Girls Doing Cute Things",
    "Family Life",
    "Iyashikei",
}

adultTags = normalTags | {
    "Ahegao",
    "Amputation",
    "Anal Sex",
    "Armpits",
    "Ashikoki",
    "Asphyxiation",
    "Blackmail",
    "Bondage",
    "Boobjob",
    "Cumflation",
    "Cunnilingus",
    "Deepthroat",
    "Defloration",
    "DILF",
    "Exhibitionism",
    "Facial",
    "Feet",
    "Fellatio",
    "Femdom",
    "Flat Chest",
    "Futanari",
    "Group Sex",
    "Handjob",
    "Human Pet",
    "Incest",
    "Inseki",
    "Irrumatio",
    "Lactation",
    "Large Breasts",
    "Masochism",
    "Masturbation",
    "MILF",
    "Nakadashi",
    "Netorare",
    "Netorase",
    "Netori",
    "Pregnant",
    "Prostitution",
    "Public Sex",
    "Rape",
    "Rimjob",
    "Sadism",
    "Scat",
    "Scissoring",
    "Sex Toys",
    "Squirting",
    "Sumata",
    "Sweat",
    "Tentacles",
    "Threesome",
    "Virginity",
    "Vore",
    "Voyeur",
    "Watersports",
}
